# Generated by Django 6.0.3 on 2026-04-07 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
