# Generated by Django 6.0.3 on 2026-04-07 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_rename_students_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='subject',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
