# Generated by Django 6.0.3 on 2026-04-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=40)),
                ('Specialization', models.CharField(max_length=100)),
                ('Experience', models.CharField(max_length=50)),
            ],
        ),
    ]
